In [1]:
import pandas as pd 
import numpy as np
from sklearn import tree
from sklearn.preprocessing import LabelEncoder

 
df=pd.read_csv('loan_approval_dataset.csv') 
df.head() 
 
df.info() 
df.keys() 
 
df.columns=df.columns.str.strip() 
 
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4269 non-null   int64
 1    no_of_dependents          4269 non-null   int64
 2    education                 4269 non-null   object
 3    self_employed             4269 non-null   object
 4    income_annum              4269 non-null   int64
 5    loan_amount               4269 non-null   int64
 6    loan_term                 4269 non-null   int64
 7    cibil_score               4269 non-null   int64
 8    residential_assets_value  4269 non-null   int64
 9    commercial_assets_value   4269 non-null   int64
 10   luxury_assets_value       4269 non-null   int64
 11   bank_asset_value          4269 non-null   int64
 12   loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB

Index(['loan_id', 'no_of_dependents', 'education', 'self_employed',
       'income_annum', 'loan_amount', 'loan_term', 'cibil_score',
       'residential_assets_value', 'commercial_assets_value',
       'luxury_assets_value', 'bank_asset_value', 'loan_status'],
      dtype='object')

In [2]:
df.drop(columns = ['loan_id'],inplace = True )

In [3]:
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [4]:
df.shape

(4269, 12)

In [5]:
df.isnull().sum()

no_of_dependents            0
education                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
cibil_score                 0
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
loan_status                 0
dtype: int64

In [6]:
df['Assert'] = df['residential_assets_value'] + df['commercial_assets_value'] + df['luxury_assets_value'] + df['bank_asset_value']

In [7]:
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status,Assert
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved,50700000
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected,17000000
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected,57700000
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected,52700000
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected,55000000

In [8]:
df.tail()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status,Assert
4264,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected,7400000
4265,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved,20000000
4266,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected,39000000
4267,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved,28800000
4268,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved,77300000

In [9]:
df.drop(columns = ['residential_assets_value','commercial_assets_value','luxury_assets_value','bank_asset_value'],inplace = True)

In [10]:
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assert
0,2,Graduate,No,9600000,29900000,12,778,Approved,50700000
1,0,Not Graduate,Yes,4100000,12200000,8,417,Rejected,17000000
2,3,Graduate,No,9100000,29700000,20,506,Rejected,57700000
3,3,Graduate,No,8200000,30700000,8,467,Rejected,52700000
4,5,Not Graduate,Yes,9800000,24200000,20,382,Rejected,55000000

In [11]:
df.tail()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assert
4264,5,Graduate,Yes,1000000,2300000,12,317,Rejected,7400000
4265,0,Not Graduate,Yes,3300000,11300000,20,559,Approved,20000000
4266,2,Not Graduate,No,6500000,23900000,18,457,Rejected,39000000
4267,1,Not Graduate,No,4100000,12800000,8,780,Approved,28800000
4268,1,Graduate,No,9200000,29700000,10,607,Approved,77300000

In [12]:
df['education'].unique()

array([' Graduate', ' Not Graduate'], dtype=object)

In [13]:
df['education']=df['education'].apply(lambda x:x.strip())

In [14]:
df['education'].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [15]:
df['education']=df['education'].replace(['Graduate','Not Graduate'],[1,0])

C:\Users\pc14\AppData\Local\Temp\ipykernel_768\2487469019.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['education']=df['education'].replace(['Graduate','Not Graduate'],[1,0])

In [16]:
df

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assert
0,2,1,No,9600000,29900000,12,778,Approved,50700000
1,0,0,Yes,4100000,12200000,8,417,Rejected,17000000
2,3,1,No,9100000,29700000,20,506,Rejected,57700000
3,3,1,No,8200000,30700000,8,467,Rejected,52700000
4,5,0,Yes,9800000,24200000,20,382,Rejected,55000000
...,...,...,...,...,...,...,...,...,...
4264,5,1,Yes,1000000,2300000,12,317,Rejected,7400000
4265,0,0,Yes,3300000,11300000,20,559,Approved,20000000
4266,2,0,No,6500000,23900000,18,457,Rejected,39000000
4267,1,0,No,4100000,12800000,8,780,Approved,28800000
4268,1,1,No,9200000,29700000,10,607,Approved,77300000

In [17]:
df['loan_status'].unique()

array([' Approved', ' Rejected'], dtype=object)

In [18]:
df['loan_status']=df['loan_status'].apply(lambda x:x.strip())

In [19]:
df['loan_status'].unique()

array(['Approved', 'Rejected'], dtype=object)

In [20]:
df['loan_status']=df['loan_status'].replace(['Approved','Rejected'],[1,0])

C:\Users\pc14\AppData\Local\Temp\ipykernel_768\294652728.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['loan_status']=df['loan_status'].replace(['Approved','Rejected'],[1,0])

In [21]:
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assert
0,2,1,No,9600000,29900000,12,778,1,50700000
1,0,0,Yes,4100000,12200000,8,417,0,17000000
2,3,1,No,9100000,29700000,20,506,0,57700000
3,3,1,No,8200000,30700000,8,467,0,52700000
4,5,0,Yes,9800000,24200000,20,382,0,55000000

In [22]:
df.tail()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assert
4264,5,1,Yes,1000000,2300000,12,317,0,7400000
4265,0,0,Yes,3300000,11300000,20,559,1,20000000
4266,2,0,No,6500000,23900000,18,457,0,39000000
4267,1,0,No,4100000,12800000,8,780,1,28800000
4268,1,1,No,9200000,29700000,10,607,1,77300000

In [23]:
df['self_employed'].unique()

array([' No', ' Yes'], dtype=object)

In [24]:
df['self_employed']=df['self_employed'].apply(lambda x:x.strip())

In [25]:
df['self_employed'].unique()

array(['No', 'Yes'], dtype=object)

In [26]:
df['self_employed']=df['self_employed'].replace(['Yes','No'],[1,0])

C:\Users\pc14\AppData\Local\Temp\ipykernel_768\1362126969.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['self_employed']=df['self_employed'].replace(['Yes','No'],[1,0])

In [27]:
df.tail()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assert
4264,5,1,1,1000000,2300000,12,317,0,7400000
4265,0,0,1,3300000,11300000,20,559,1,20000000
4266,2,0,0,6500000,23900000,18,457,0,39000000
4267,1,0,0,4100000,12800000,8,780,1,28800000
4268,1,1,0,9200000,29700000,10,607,1,77300000

In [28]:
X=df.drop(columns=['loan_status']) 
y=df['loan_status']

In [29]:
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [32]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((3415, 8), (854, 8), (3415,), (854,))

In [33]:
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
scaler = StandardScaler()

In [36]:
x_train_scaled = scaler.fit_transform(x_train)

In [37]:
x_test_scaled = scaler.transform(x_test)

In [38]:
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

In [39]:
from sklearn.linear_model import LogisticRegression

In [40]:
model = LogisticRegression()

In [41]:
model.fit(x_train_scaled, y_train)

LogisticRegression()

In [42]:
model.score(x_test_scaled, y_test)

0.905152224824356

In [43]:
model.predict(x_test_scaled)

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1], dtype=int64)

In [44]:
pred_data = pd.DataFrame([['2','1','0','9600000','29900000','12','778','50700000']],columns=['no_of_dependents','education','self_employed','income_annum','loan_amount','loan_term','cibil_score','Assert'])

In [45]:
pred_data = scaler.transform(pred_data)

In [46]:
model.predict(pred_data)

array([1], dtype=int64)

In [47]:
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

In [48]:
import pickle as pk

In [49]:
pk.dump(model,open('model.pkl','wb'))

In [50]:
pk.dump(scaler,open("scaler.pkl",'wb'))

In [51]:
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

In [52]:
d_model = tree.DecisionTreeRegressor()

In [53]:
d_model.fit(x_train_scaled, y_train)

DecisionTreeRegressor()

In [54]:
d_model.score(x_test_scaled, y_test)

0.944886416971745

In [55]:
d_model.predict(x_test_scaled)

array([0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1.,
       0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0.,
       1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0.,
       0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1.,
       1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1.,
       0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0.,
       0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1.,
       0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0.,
       1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
       0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0.,
       0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0.,
       1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1.,
       1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1.,
       1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1.,
       0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1.,
       0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1.,
       0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1.,
       0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1.,
       1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0.,
       1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 0., 0.])

In [56]:
d_pred_data = pd.DataFrame([['2','1','0','9600000','29900000','12','778','50700000']],columns=['no_of_dependents','education','self_employed','income_annum','loan_amount','loan_term','cibil_score','Assert'])

In [57]:
d_pred_data = scaler.transform(d_pred_data)

In [58]:
d_model.predict(d_pred_data)

array([1.])

In [59]:
pk.dump(d_model,open('d_model.pkl','wb'))

In [60]:
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

In [61]:
from sklearn.ensemble import RandomForestRegressor

In [62]:
regressor = RandomForestRegressor(n_estimators=100)

In [63]:
regressor.fit(x_train_scaled, y_train)

RandomForestRegressor()

In [64]:
regressor.score(x_test_scaled, y_test)

0.9598111752557965

In [65]:
regressor.predict(x_test_scaled)

array([0.  , 1.  , 0.  , 1.  , 1.  , 1.  , 1.  , 0.  , 1.  , 0.  , 0.  ,
       1.  , 1.  , 0.  , 0.  , 1.  , 1.  , 0.89, 0.57, 0.  , 1.  , 0.  ,
       0.  , 0.  , 1.  , 1.  , 1.  , 1.  , 1.  , 0.  , 1.  , 0.  , 0.  ,
       1.  , 0.  , 0.  , 1.  , 1.  , 1.  , 0.  , 0.  , 1.  , 0.98, 1.  ,
       0.68, 1.  , 0.97, 1.  , 1.  , 0.  , 1.  , 0.54, 0.  , 1.  , 0.94,
       1.  , 1.  , 1.  , 0.31, 1.  , 1.  , 1.  , 0.  , 0.  , 0.  , 1.  ,
       1.  , 1.  , 0.97, 1.  , 1.  , 1.  , 0.98, 1.  , 0.  , 1.  , 0.  ,
       0.95, 1.  , 1.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.97, 1.  ,
       0.  , 0.  , 1.  , 0.  , 0.97, 0.  , 0.  , 1.  , 0.  , 1.  , 1.  ,
       1.  , 1.  , 0.32, 1.  , 0.  , 0.  , 1.  , 0.06, 1.  , 1.  , 1.  ,
       1.  , 1.  , 0.  , 0.49, 0.  , 0.76, 0.98, 0.99, 0.31, 1.  , 0.  ,
       0.96, 0.  , 0.  , 1.  , 1.  , 1.  , 0.  , 0.83, 0.98, 1.  , 0.  ,
       1.  , 0.  , 0.7 , 1.  , 1.  , 0.  , 0.99, 1.  , 1.  , 1.  , 1.  ,
       0.  , 0.29, 1.  , 0.  , 0.99, 0.  , 0.94, 1.  , 0.61, 0.  , 0.  ,
       1.  , 1.  , 1.  , 0.  , 0.68, 1.  , 0.  , 1.  , 1.  , 1.  , 0.  ,
       1.  , 1.  , 1.  , 0.  , 1.  , 0.96, 0.  , 1.  , 1.  , 0.  , 1.  ,
       0.99, 0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.6 , 1.  , 1.  ,
       1.  , 0.  , 1.  , 1.  , 0.  , 0.  , 0.  , 1.  , 1.  , 0.1 , 0.99,
       1.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 1.  , 0.91, 1.  ,
       1.  , 1.  , 0.  , 0.04, 1.  , 1.  , 1.  , 0.  , 1.  , 1.  , 1.  ,
       1.  , 1.  , 0.97, 0.  , 1.  , 1.  , 1.  , 0.75, 1.  , 0.69, 0.14,
       0.  , 0.63, 0.  , 1.  , 1.  , 1.  , 1.  , 0.  , 1.  , 0.  , 0.  ,
       1.  , 1.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.99, 1.  , 1.  , 1.  ,
       1.  , 0.  , 0.  , 0.  , 1.  , 0.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
       1.  , 0.99, 1.  , 0.  , 0.  , 1.  , 1.  , 1.  , 0.  , 1.  , 1.  ,
       1.  , 1.  , 0.  , 1.  , 0.97, 0.  , 0.55, 1.  , 1.  , 0.23, 1.  ,
       1.  , 0.02, 0.  , 1.  , 1.  , 1.  , 0.  , 1.  , 0.1 , 1.  , 1.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 1.  , 1.  , 0.  , 1.  , 1.  , 1.  ,
       1.  , 1.  , 1.  , 0.25, 1.  , 0.84, 1.  , 1.  , 1.  , 0.99, 0.  ,
       1.  , 1.  , 1.  , 1.  , 1.  , 0.25, 0.  , 1.  , 0.02, 0.  , 0.  ,
       1.  , 0.  , 1.  , 1.  , 0.98, 0.  , 0.  , 0.98, 1.  , 0.84, 1.  ,
       1.  , 0.52, 1.  , 0.95, 0.  , 0.  , 1.  , 1.  , 0.  , 1.  , 1.  ,
       0.  , 0.  , 1.  , 1.  , 1.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.97,
       1.  , 0.06, 0.  , 0.  , 1.  , 1.  , 1.  , 1.  , 0.  , 1.  , 0.37,
       0.  , 0.  , 0.  , 0.  , 1.  , 1.  , 1.  , 0.  , 1.  , 0.  , 1.  ,
       1.  , 0.89, 1.  , 1.  , 1.  , 0.  , 1.  , 1.  , 1.  , 1.  , 0.  ,
       1.  , 0.  , 0.93, 1.  , 0.  , 1.  , 0.  , 1.  , 1.  , 1.  , 0.  ,
       0.  , 1.  , 1.  , 0.  , 1.  , 1.  , 0.53, 1.  , 0.  , 0.  , 0.  ,
       0.  , 1.  , 0.87, 0.  , 0.  , 1.  , 1.  , 1.  , 0.  , 1.  , 1.  ,
       1.  , 0.  , 1.  , 1.  , 1.  , 0.01, 0.  , 0.  , 0.  , 1.  , 1.  ,
       0.  , 1.  , 1.  , 0.  , 1.  , 0.42, 1.  , 1.  , 1.  , 1.  , 0.  ,
       1.  , 0.  , 1.  , 0.59, 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
       0.  , 0.  , 1.  , 1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 1.  , 1.  ,
       0.  , 0.98, 1.  , 0.  , 0.  , 1.  , 1.  , 1.  , 1.  , 0.  , 1.  ,
       1.  , 1.  , 1.  , 1.  , 0.  , 0.98, 1.  , 0.  , 0.77, 0.96, 0.  ,
       1.  , 0.  , 0.  , 0.  , 1.  , 1.  , 1.  , 1.  , 0.  , 1.  , 1.  ,
       0.  , 1.  , 1.  , 1.  , 0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 1.  ,
       1.  , 1.  , 0.  , 1.  , 1.  , 1.  , 0.  , 1.  , 1.  , 1.  , 0.  ,
       1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 0.  , 1.  , 0.  , 0.  ,
       1.  , 1.  , 0.  , 0.95, 0.97, 0.  , 1.  , 1.  , 0.84, 0.  , 1.  ,
       0.  , 1.  , 1.  , 1.  , 1.  , 0.03, 1.  , 1.  , 0.04, 0.  , 1.  ,
       1.  , 1.  , 1.  , 0.  , 0.  , 0.99, 0.  , 1.  , 0.43, 0.07, 1.  ,
       1.  , 0.  , 1.  , 0.  , 1.  , 0.  , 1.  , 1.  , 1.  , 0.  , 1.  ,
       1.  , 1.  , 0.  , 1.  , 0.4 , 0.  , 1.  , 1.  , 1.  , 0.  , 1.  ,
       1.  , 1.  , 1.  , 0.  , 1.  , 0.44, 0.  , 1.  , 1.  , 0.  , 1.  ,
       1.  , 1.  , 1.  , 1.  , 0.41, 1.  , 0.71, 0.  , 1.  , 1.  , 1.  ,
       0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 1.  , 1.  , 1.  , 0.97, 1.  ,
       0.  , 1.  , 1.  , 0.  , 1.  , 1.  , 1.  , 1.  , 0.  , 1.  , 1.  ,
       0.  , 1.  , 1.  , 0.  , 0.98, 1.  , 1.  , 1.  , 1.  , 1.  , 0.  ,
       0.98, 1.  , 1.  , 1.  , 1.  , 0.  , 1.  , 1.  , 0.  , 1.  , 1.  ,
       0.  , 1.  , 1.  , 0.  , 0.  , 1.  , 0.  , 1.  , 1.  , 1.  , 1.  ,
       0.  , 1.  , 1.  , 0.  , 0.  , 0.  , 1.  , 1.  , 0.44, 0.  , 1.  ,
       1.  , 0.  , 1.  , 1.  , 1.  , 1.  , 0.  , 1.  , 0.  , 0.  , 1.  ,
       0.  , 1.  , 1.  , 0.  , 0.  , 1.  , 1.  , 0.  , 0.  , 1.  , 0.  ,
       0.  , 1.  , 0.  , 0.  , 0.44, 1.  , 1.  , 0.  , 0.  , 1.  , 0.  ,
       0.  , 1.  , 0.02, 1.  , 1.  , 0.  , 0.  , 0.97, 0.  , 1.  , 0.  ,
       1.  , 1.  , 0.99, 0.21, 1.  , 1.  , 1.  , 1.  , 0.98, 0.  , 1.  ,
       0.  , 0.14, 1.  , 1.  , 0.  , 0.01, 1.  , 0.  , 1.  , 1.  , 0.  ,
       0.  , 0.  , 0.32, 0.  , 1.  , 1.  , 0.03, 1.  , 1.  , 1.  , 0.  ,
       0.  , 1.  , 0.  , 1.  , 0.  , 1.  , 1.  , 0.99, 0.  , 0.  , 1.  ,
       0.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 0.  , 1.  , 1.  , 1.  ,
       1.  , 1.  , 1.  , 0.  , 0.  , 1.  , 0.  , 0.99, 1.  , 1.  , 0.88,
       0.02, 0.  , 0.  , 0.  , 1.  , 0.  , 1.  , 1.  , 0.96, 0.  , 1.  ,
       1.  , 1.  , 0.  , 0.87, 1.  , 1.  , 0.  , 1.  , 0.74, 0.  , 1.  ,
       0.  , 1.  , 0.96, 0.  , 1.  , 1.  , 1.  , 0.  , 0.  , 1.  , 1.  ,
       1.  , 1.  , 0.47, 0.98, 1.  , 0.  , 0.4 , 0.  , 1.  , 0.99, 0.  ,
       1.  , 0.  , 1.  , 0.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 0.  ,
       1.  , 0.  , 1.  , 1.  , 1.  , 0.  , 0.  ])

In [66]:
r_pred_data = pd.DataFrame([['2','1','0','9600000','29900000','12','778','50700000']],columns=['no_of_dependents','education','self_employed','income_annum','loan_amount','loan_term','cibil_score','Assert'])

In [67]:
r_pred_data = scaler.transform(r_pred_data)

In [68]:
regressor.predict(r_pred_data)

array([1.])

In [69]:
pk.dump(regressor,open('regressor.pkl','wb'))

In [70]:
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

In [71]:
from sklearn.naive_bayes import GaussianNB

In [72]:
n_model = GaussianNB()

In [73]:
n_model.fit(x_train_scaled, y_train)

GaussianNB()

In [74]:
n_model.score(x_test_scaled, y_test)

0.9391100702576113

In [75]:
n_model.predict(x_test_scaled)

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0], dtype=int64)

In [76]:
n_pred_data = pd.DataFrame([['2','1','0','9600000','29900000','12','778','50700000']],columns=['no_of_dependents','education','self_employed','income_annum','loan_amount','loan_term','cibil_score','Assert'])

In [77]:
n_pred_data = scaler.transform(n_pred_data)

In [78]:
n_model.predict(n_pred_data)

array([1], dtype=int64)

In [79]:
pk.dump(regressor,open('n_model.pkl','wb'))